#!/bin/zsh

alias g='git'
alias y='yadm'
alias cat='bat'
alias ls='exa'
alias vim='nvim'
alias ping='prettyping --nolegend'
alias top='htop'
alias du='ncdu --color dark --r -x'
alias preview="fzf --preview 'bat --color \"always\" {}'"
alias vpn='nordvpn'
alias calc='ipython --profile=calc'
alias gradle='./gradlew'
alias ..2='cd ../../'
alias ..3='cd ../../../'
alias ..4='cd ../../../../'
alias ..5='cd ../../../../../'
alias ..6='cd ../../../../../../'
alias ..7='cd ../../../../../../../'
alias err='echo >&2'
alias del='trash'
alias res='trash-restore'
alias rm='err This command has been disabled. Use following command instead: del '

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index
