#!/bin/zsh

alias cat='bat'
alias ls='exa'
alias ping='prettyping --nolegend'
alias top='htop'
alias du='ncdu --color dark --r -x'
alias preview="fzf --preview 'bat --color \"always\" {}'"
alias vpn='nordvpn'
alias calc='python -i -c "from math import *"'
alias gradle='./gradlew'
alias ..2='cd ../../'
alias ..3='cd ../../../'
alias ..4='cd ../../../../'
alias ..5='cd ../../../../../'
alias ..6='cd ../../../../../../'
alias ..7='cd ../../../../../../../'
alias err='echo >&2'
alias del='trash'
alias res='trash-restore'
alias rm='err This command has been disabled. Use following command instead: del '

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# NVM lazy loading
alias nvm='unalias nvm; unalias node; unalias npm; nvm_load; nvm $@'
alias node='unalias nvm; unalias node; unalias npm; nvm_load; node $@'
alias npm='unalias nvm; unalias node; unalias npm; nvm_load; npm $@'

# Ruby Gems lazy loading
alias gem='unalias gem; { [ -z ${GEM_HOME} ] && gem_load }; gem "$@"'


