#!/bin/bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

set -eu

readonly logfile="/tmp/$(basename "$0").log"
info()    { echo "[INFO]    $*" | tee -a "$logfile" >&2 ; }
warning() { echo "[WARNING] $*" | tee -a "$logfile" >&2 ; }
error()   { echo "[ERROR]   $*" | tee -a "$logfile" >&2 ; }
fatal()   { echo "[FATAL]   $*" | tee -a "$logfile" >&2 ; exit 1 ; }

todofile="$HOME/todo.md"

os="{{ yadm.os }}"
class="{{ yadm.class }}"
distro="{{ yadm.distro }}"

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

info "OS: $os"
info "CLASS: $class"
info "DISTRO: $distro"

rm -f "$todofile" || true

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    fatal "Error: bootstrap directory '$BOOTSTRAP_D' not found"
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
	info "Executing script '$(basename "$bootstrap")'"

        if ! "$bootstrap"; then
            fatal "Error: bootstrap '$bootstrap' failed"
        fi
    fi
done

info "Done! Please review '$todofile' file to proceed"
info "$ cat $todofile:"
cat $todofile