#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

import re
from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    fulltext = "<span color='red'><span font='FontAwesome'>\uf00d \uf240</span></span>"
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is 
    # available for each battery separately, although state and remaining 
    # time for overall block is shown in the status of the first battery 
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    time = ""
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            if not time:
                time = commasplitstatus[-1].strip()
                # check if it matches a time
                time = re.match(r"(\d+):(\d+)", time)
                if time:
                    time = ":".join(time.groups())
                    timeleft = " ({})".format(time)
                else:
                    timeleft = ""

            p = int(commasplitstatus[1].rstrip("%\n"))
            if p>0:
                percentleft_batteries.append(p)
            commasplitstatus_batteries.append(commasplitstatus)
    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    if percentleft_batteries:
        percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))
    else:
        percentleft = 0

    # stands for charging
    FA_LIGHTNING = "<span color='yellow'><span font='FontAwesome'>\uf0e7</span></span>"

    # stands for plugged in
    FA_PLUG = "<span font='FontAwesome'>\uf1e6</span>"

    # stands for using battery
    FA_BATTERY_FULL = "<span font='FontAwesome'>\uf240</span>"
    FA_BATTERY_3 = "<span font='FontAwesome'>\uf241</span>"
    FA_BATTERY_2 = "<span font='FontAwesome'>\uf242</span>"
    FA_BATTERY_1 = "<span font='FontAwesome'>\uf243</span>"
    FA_BATTERY_EMPTY = "<span font='FontAwesome'>\uf244</span>"

    # stands for unknown status of battery
    FA_QUESTION = "<span font='FontAwesome'>\uf128</span>"

    def dischargingicon(percent):
        # 0 - 9 | 10 - 29 | 30 - 69 | 70 - 89 | 90 - 100
        if percent < 10:
            return FA_BATTERY_EMPTY
        if percent < 30:
            return FA_BATTERY_1
        if percent < 70:
            return FA_BATTERY_2
        if percent < 90:
            return FA_BATTERY_3        
        return FA_BATTERY_FULL

    if state == "Discharging":
        fulltext = " " + dischargingicon(percentleft) + " "
    elif state == "Full":
        fulltext = " " + FA_PLUG + " "
        timeleft = ""
    elif state == "Unknown":
        fulltext = " " + FA_QUESTION + " " + FA_BATTERY_EMPTY + " "
        timeleft = ""
    else:
        #fulltext = FA_LIGHTNING + " " + FA_PLUG + " "
        fulltext = " " + FA_PLUG + " "

    def color(state, percent):
        if state == "Discharging":
            if percent < 10:            
                return "#FF0000"
            if percent < 20:
                return "#FF3300"
            if percent < 30:
                return "#FF6600"
            if percent < 40:
                return "#FF9900"
            if percent < 50:
                return "#FFCC00"
            return "#FFFFFF"
        else:
            if percent < 10:                
                return "#FF0000"
            if percent < 20:
                return "#FF3300"
            if percent < 30:
                return "#FF6600"
            if percent < 40:
                return "#FF9900"
            if percent < 50:
                return "#FFCC00"
            if percent < 60:
                return "#DDFF00"
            if percent < 70:
                return "#AAFF00"
            if percent < 80:
                return "#77FF66"
            if percent < 90:
                return "#44FF00"
            if percent < 100:
                return "#00FF00" 
            return "#00DDFF"

    form =  '<span color="{}">{}%</span> '
    fulltext += form.format(color(state, percentleft), percentleft)    

print(fulltext)
print(fulltext)
if percentleft < 10 and state == "Discharging":
    exit(33)

