#!/bin/bash

# Bootstrap your base working environment configured with ~/.config/dotfile/bootstrap.d scripts

set -eu

readonly logfile="/tmp/yadm-bootstrap.log"
readonly lockfile="/tmp/yadm-bootstrap.lock"
info()    { echo "[INFO]    $*" | tee -a "$logfile" >&2 ; }
warning() { echo "[WARNING] $*" | tee -a "$logfile" >&2 ; }
error()   { echo "[ERROR]   $*" | tee -a "$logfile" >&2 ; }
fatal()   { echo "[FATAL]   $*" | tee -a "$logfile" >&2 ; exit 1 ; }

todofile="$HOME/todo.md"

os="Linux"
class=""
distro="arch"

# Directory to look for bootstrap executables in
BOOTSTRAP_D="$HOME/.config/dotfile/bootstrap.d"

info "OS: $os"
info "CLASS: $class"
info "DISTRO: $distro"

rm -f "$todofile" || true

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    fatal "Error: bootstrap directory '$BOOTSTRAP_D' not found"
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
	info "Executing script '$(basename "$bootstrap")'"

        if ! "$bootstrap" "$logfile" "$lockfile" "${os:-' '}" "${distro:-' '}" "${class:-' '}"; then
            fatal "Error: bootstrap '$bootstrap' failed"
        fi
    fi
done

info "Done! Please review '$todofile' file to proceed"
info "$ cat $todofile:"
cat $todofile
