#!/bin/bash

RESOLUTION=$(xdpyinfo | awk '/dimensions/{print $2}')

DIR=~/.wallpapers

mkdir -p "$DIR"


check-wallpaper-in-blacklist() {
	cat "$DIR/blacklist" | grep "$(cat "$DIR/wallpaper" | md5sum | cut -d ' ' -f1)"	
	if [ $? -eq 0 ] ; then
		echo "Wallpaper from blacklist has been drawn. Redrawing new wallpaper..."
		change-wallpaper
	fi
}

change-wallpaper() {
	wget "https://source.unsplash.com/random/${RESOLUTION}" --no-check-certificate -o /dev/null -O "$DIR/wallpaper.new" &> /dev/null
	
	if [ $? -eq 0 ] ; then
		rm "$DIR/wallpaper" &> /dev/null
		mv "$DIR/wallpaper.new" "$DIR/wallpaper"
		check-wallpaper-in-blacklist
		update-wallpaper
	else
		set-default
	fi
}

block-wallpaper() {
	echo "# $(date)" >> "$DIR/blacklist"
	md5sum "$DIR/wallpaper" >> "$DIR/blacklist"
	echo "Current wallpaper has been add to blacklist"
	change-wallpaper
}

save-wallpaper() {
	mkdir -p "$DIR/favourites"
	DEST="$DIR/favourites/$(cat "$DIR/wallpaper" | md5sum | cut -d ' ' -f1)"
	cp "$DIR/wallpaper" "$DEST"
	echo "Wallpaper saved as $DEST"
}

set-default() {
	cp "$DIR/default" "$DIR/wallpaper"
	update-wallpaper
}

update-wallpaper() {
	DISPLAY=:0.0 nitrogen --set-zoom-fill "$DIR/wallpaper"
}

display-help() {
	cat <<EOF >&2
Usage: $(basename $0) COMMAND

Unsplash wallpaper management tool.

Available commands:
  * change - draw new wallpaper from unsplash.com
  * block - add current wallpaper to blacklist and immediately draw new wallpaper
  * save - save wallpaper to favourites
  * default - set current wallpaper to default
  * help - display this help
EOF
}

case $1 in
	change) change-wallpaper ;;
	block) block-wallpaper ;;
	save) save-wallpaper ;;
	default) set-default ;;
	help) display-help ;;
	*) display-help ;;
esac

