#!/bin/zsh

prompt_opts=(subst percent)

prompt_bartek_precmd() {
  autoload -Uz vcs_info 
  vcs_info  
  zstyle ':vcs_info:*'                  enable            git
  zstyle ':vcs_info:git:*'              stagedstr         "%F{green}"
  zstyle ':vcs_info:git:*'              unstagedstr       "%F{cyan}"
  zstyle ':vcs_info:git*+set-message:*' hooks             git-untracked
  zstyle ':vcs_info:git:*'              check-for-changes true
  zstyle ':vcs_info:git:*'              formats           '%b%c%u%m%a'
}

+vi-git-untracked() {
  if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
    git status --porcelain | grep -m 1 '^??' &>/dev/null
  then
    hook_com[misc]='%F{magenta}'
  fi
}

git_info() {
  [ ! -z "$vcs_info_msg_0_" ] && echo "$vcs_info_msg_0_ "
}

prompt_bartek_setup() {  
  add-zsh-hook precmd prompt_bartek_precmd
  sign='%(?.%F{blue}λ%f.%F{red}%f)'
  RPS1='%F{green}%*%f'
  PS1=$'%F{green}%~ %F{yellow}$(git_info)$sign '
}

prompt_bartek_setup $@